# Project automation commands for setup, running, testing,
# formatting, migrations, and cleanup.

.PHONY: help venv install run test test-ws migrate makemigration clean-db clean

PYTHON := python3
VENV := venv
BIN := $(VENV)/bin
PIP := $(BIN)/pip
UVICORN := $(BIN)/uvicorn
PYTEST := $(BIN)/pytest
ALEMBIC := $(BIN)/alembic

help:
	@echo "Targets:"
	@echo "  make venv                        Create virtual environment"
	@echo "  make install                     Install development dependencies"
	@echo "  make run                         Run API server with reload"
	@echo "  make test                        Run all tests"
	@echo "  make test-ws                     Run WebSocket-related tests"
	@echo "  make migrate                     Apply Alembic migrations"
	@echo "  make makemigration m='msg'       Create autogenerated migration"
	@echo "  make clean                       Remove Python and pytest caches"
	@echo "  make clean-db                    Remove local SQLite database files"

# Create the Python virtual environment.
venv:
	$(PYTHON) -m venv $(VENV)
	$(PIP) install -U pip

# Install development dependencies into the virtual environment.
install: venv
	$(PIP) install -r requirements-dev.txt

# Start the FastAPI development server with auto-reload enabled.
run:
	$(UVICORN) main:app --reload

# Run the full test suite.
test:
	$(PYTEST) -q

# Run only WebSocket-related tests with verbose output.
test-ws:
	$(PYTEST) -q -k "ws" -s -vv

# Apply all Alembic migrations to the current database.
migrate:
	$(ALEMBIC) upgrade head

# Generate a new Alembic migration with autogeneration.
makemigration:
	$(ALEMBIC) revision --autogenerate -m "$(m)"

# Remove Python cache folders and pytest cache.
clean:
	rm -rf __pycache__ .pytest_cache
	find . -type d -name "__pycache__" -exec rm -rf {} + || true

# Remove local SQLite database files such as tasks.db and test.db.
clean-db:
	rm -f *.db test.db tasks.db