"""set null on last_read_message_id

Revision ID: 979af1de7194
Revises: ffa845ee52ac
Create Date: 2026-03-31 16:51:01.504743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979af1de7194'
down_revision: Union[str, Sequence[str], None] = 'ffa845ee52ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_reads', 'last_read_message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('message_reads_last_read_message_id_fkey'), 'message_reads', type_='foreignkey')
    op.create_foreign_key(None, 'message_reads', 'messages', ['last_read_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_reads', type_='foreignkey')
    op.create_foreign_key(op.f('message_reads_last_read_message_id_fkey'), 'message_reads', 'messages', ['last_read_message_id'], ['id'])
    op.alter_column('message_reads', 'last_read_message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
